before_build:
  - nuget restore

test: off

image: Visual Studio 2017

build:
  project: Agoda.LoadBalancing.sln

after_build:
  - ps: .\tools\publish.ps1

artifacts:
  - path: '**\*.nupkg'
    name: NugetPackage
  
deploy:
  provider: NuGet
  api_key:
    secure: VubFf6ZLPQHaPO9vRTftkmJWYFuGUxWwm6+gcb8KndKNgOXmNY9KjH3E+oK9VJ2V
  skip_symbols: true
  artifact: /.*\.nupkg/
